### ISSUE TITLE
Question: debugging and testing

### ISSUE THREAD

**Issue by jorisdebock** [cezarypiatek/SmartCodeGenerator#2]
How should I go about debugging and (unit)testing my own code generator plugin?

**Comment by cezarypiatek** [comment]
Hi,
Currently, there is no test kit for `SmartCodeGenerator` plugins, but I could implement something like that. In terms of debugging, the easiest option is to use [Debugger.Launch](https://docs.microsoft.com/en-US/dotnet/api/system.diagnostics.debugger.launch?view=netframework-4.8) inside your plugin code

**Comment by cezarypiatek** [comment]
I've finished the first version of TestKit. This should address both issues: debugging and testing. I need a little more time to prepare a release.

**Comment by cezarypiatek** [comment]
[SmartCodeGenerator.TestKit](https://www.nuget.org/packages/SmartCodeGenerator.TestKit/) has been released. An example usage can be found here https://github.com/cezarypiatek/MappingGenerator/blob/master/MappingGenerator/MappingGenerator/MappingGenerator.Test/OnBuildGenerator/OnBuildGeneratorTest.cs

You should also be able to debug your extensions using unit tests.
